//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.LicenceSigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantasy.LicenceSigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DSAKeyValue&gt;&lt;P&gt;pNmoVnPhu8rkMqg6uB6WUCm6GqZgzmThr2VC9hk0IBmphxSXZ8hBvjb4L6F44tzWCP5hjh8AuNKvEj/xo0Fxqq1WY7sMeDULf+dpmEK9SF57q4+avzFgo3XD/GBSQmRdbyllJHMw0ByFESAFtth4V3ruProvOyyAuCpyrcm21Ac=&lt;/P&gt;&lt;Q&gt;xGgzJOZHsX7FVrJmF7nD1reKGU0=&lt;/Q&gt;&lt;G&gt;dcAwjh26TA66jjAulcub2HUHGMQgyeIDeTvqPAIrPh08bLO886r8e3hkebnLQY1rDasmgCElbBzCNXZUkyZ2H8EYu8ZYuOSdqn/3r0kL61T6nAdSlac0uYiLL5yLAzzKFhZ9bb+pcvhMG6bOsyokgAp+ATFeR2G6wC4zKuW9ykc=&lt;/G&gt;&lt;Y&gt;ToSNpB4eBi2RW540zqN41+vv7ud/J4KxfQfxmLiF8P7GCV1qaVq8MtM3IPCsmSuN8XfbQhElMWz5x5wqBLBLrnDU0dyg3vhrujLiZLZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FantasyPtyKey {
            get {
                return ResourceManager.GetString("FantasyPtyKey", resourceCulture);
            }
        }
    }
}
