//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Windows.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Windows.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation..
        /// </summary>
        public static string Automation_OperationCannotBePerformed {
            get {
                return ResourceManager.GetString("Automation_OperationCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SelectedDates collection can be changed only in a multiple selection mode. Use the SelectedDate in a single selection mode..
        /// </summary>
        public static string Calendar_CheckSelectionMode_InvalidOperation {
            get {
                return ResourceManager.GetString("Calendar_CheckSelectionMode_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next button.
        /// </summary>
        public static string Calendar_NextButtonName {
            get {
                return ResourceManager.GetString("Calendar_NextButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayMode value is not valid..
        /// </summary>
        public static string Calendar_OnDisplayModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnDisplayModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstDayOfWeek value is not valid..
        /// </summary>
        public static string Calendar_OnFirstDayOfWeekChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnFirstDayOfWeekChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SelectedDate property cannot be set when the selection mode is None..
        /// </summary>
        public static string Calendar_OnSelectedDateChanged_InvalidOperation {
            get {
                return ResourceManager.GetString("Calendar_OnSelectedDateChanged_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectedDate value is not valid..
        /// </summary>
        public static string Calendar_OnSelectedDateChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnSelectedDateChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectionMode value is not valid..
        /// </summary>
        public static string Calendar_OnSelectionModeChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Calendar_OnSelectionModeChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous button.
        /// </summary>
        public static string Calendar_PreviousButtonName {
            get {
                return ResourceManager.GetString("Calendar_PreviousButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid..
        /// </summary>
        public static string Calendar_UnSelectableDates {
            get {
                return ResourceManager.GetString("Calendar_UnSelectableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackout Day - {0}.
        /// </summary>
        public static string CalendarAutomationPeer_BlackoutDayHelpText {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_BlackoutDayHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar button.
        /// </summary>
        public static string CalendarAutomationPeer_CalendarButtonLocalizedControlType {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_CalendarButtonLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day button.
        /// </summary>
        public static string CalendarAutomationPeer_DayButtonLocalizedControlType {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_DayButtonLocalizedControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decade.
        /// </summary>
        public static string CalendarAutomationPeer_DecadeMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_DecadeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string CalendarAutomationPeer_MonthMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_MonthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string CalendarAutomationPeer_YearMode {
            get {
                return ResourceManager.GetString("CalendarAutomationPeer_YearMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of Collection does not support changes to its SourceCollection from a thread different from the Dispatcher thread..
        /// </summary>
        public static string CalendarCollection_MultiThreadedCollectionChangeNotSupported {
            get {
                return ResourceManager.GetString("CalendarCollection_MultiThreadedCollectionChangeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateFormatInfo cannot be null..
        /// </summary>
        public static string CalendarInfo_DateFormatInfoRequired {
            get {
                return ResourceManager.GetString("CalendarInfo_DateFormatInfoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime value is in the wrong format..
        /// </summary>
        public static string DateTimeTypeConverter_FormatException {
            get {
                return ResourceManager.GetString("DateTimeTypeConverter_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Dock value &apos;{0}&apos;..
        /// </summary>
        public static string DockPanel_OnDockPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("DockPanel_OnDockPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index value &apos;{0}&apos;.
        /// </summary>
        public static string DomainUpDown_CurrentIndex_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_CurrentIndex_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InvalidInputAction value &apos;{0}&apos;.
        /// </summary>
        public static string DomainUpDown_InvalidInputAction_InvalidValue {
            get {
                return ResourceManager.GetString("DomainUpDown_InvalidInputAction_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        public static string Expander_OnExpandDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExpandDirection value &apos;{0}&apos;..
        /// </summary>
        public static string Expander_OnExpandDirectionPropertyChanged_InvalidValue1 {
            get {
                return ResourceManager.GetString("Expander_OnExpandDirectionPropertyChanged_InvalidValue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attempt to change read-only property &quot;{0}.&quot;.
        /// </summary>
        public static string InvalidAttemptToChangeReadOnlyProperty {
            get {
                return ResourceManager.GetString("InvalidAttemptToChangeReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property TimeItemsSelection..
        /// </summary>
        public static string ListTimePickerPopup_TimeItemsSelection_ReadOnly {
            get {
                return ResourceManager.GetString("ListTimePickerPopup_TimeItemsSelection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid double value &apos;{0}&apos;: valid value is of double type and within decimal range..
        /// </summary>
        public static string NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidDoubleValue_InvalidDoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Increment value &apos;{0}&apos;: valid value is of double type, within decimal range, and positive.
        /// </summary>
        public static string NumericUpDown_EnsureValidIncrementValue_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_EnsureValidIncrementValue_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DecimalPlaces value &apos;{0}&apos;: valid value is of int type and within 0 and 15 inclusive..
        /// </summary>
        public static string NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("NumericUpDown_OnDecimalPlacesPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is currently ReadOnly and should not be modified..
        /// </summary>
        public static string ObservableObjectCollection_ReadOnly {
            get {
                return ResourceManager.GetString("ObservableObjectCollection_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstructorParameters cannot be changed because ObjectDataProvider is using a user-assigned ObjectInstance..
        /// </summary>
        public static string ParameterCollection_EnsureCanChangeCollection_IsReadOnly {
            get {
                return ResourceManager.GetString("ParameterCollection_EnsureCanChangeCollection_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero..
        /// </summary>
        public static string Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Picker_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupButtonMode value &apos;{0}&apos;..
        /// </summary>
        public static string Picker_PopupButtonModeNotValid {
            get {
                return ResourceManager.GetString("Picker_PopupButtonModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be larger than or equal to 0..
        /// </summary>
        public static string Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero {
            get {
                return ResourceManager.GetString("Rating_SetItemCount_ItemCountMustBeLargerThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RatingAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be null or a number between 0 and 1..
        /// </summary>
        public static string RatingAutomationPeer_SetValue {
            get {
                return ResourceManager.GetString("RatingAutomationPeer_SetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string RatingItemAutomationPeer_GetLocalizedControlTypeCore {
            get {
                return ResourceManager.GetString("RatingItemAutomationPeer_GetLocalizedControlTypeCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elementName should not be empty..
        /// </summary>
        public static string ResolveElementNameEventArgs_ctor_ElementNameEmpty {
            get {
                return ResourceManager.GetString("ResolveElementNameEventArgs_ctor_ElementNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin action is not valid at this moment..
        /// </summary>
        public static string Spinner_SpinNotValid {
            get {
                return ResourceManager.GetString("Spinner_SpinNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupMinutesInterval &apos;{0}&apos;. The interval can be set to 0 (no interval) to and including 59..
        /// </summary>
        public static string TimeInput_PopupMinutesInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupMinutesInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupSecondsInterval &apos;{0}&apos;.The interval can be set to 0 (no interval) to and including 59..
        /// </summary>
        public static string TimeInput_PopupSecondsInterval_InvalidValue {
            get {
                return ResourceManager.GetString("TimeInput_PopupSecondsInterval_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set the PopupProperty in a style. Please use PopupTemplate..
        /// </summary>
        public static string TimePicker_PopupSetInStyle {
            get {
                return ResourceManager.GetString("TimePicker_PopupSetInStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PopupTimeSelectionMode for this popup, value &apos;{0}&apos;..
        /// </summary>
        public static string TimePicker_PopupTimeSelectionModeNotValid {
            get {
                return ResourceManager.GetString("TimePicker_PopupTimeSelectionModeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set read-only property TimeHintContent..
        /// </summary>
        public static string TimeUpDown_OnTimeHintContentChanged {
            get {
                return ResourceManager.GetString("TimeUpDown_OnTimeHintContentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not in a TreeView..
        /// </summary>
        public static string TreeViewExtensions_GetDepth_NotInTreeView {
            get {
                return ResourceManager.GetString("TreeViewExtensions_GetDepth_NotInTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        public static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        public static string TypeConverters_Convert_CannotConvert1 {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot convert from &apos;{1}&apos;..
        /// </summary>
        public static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot convert from &apos;{1}&apos;..
        /// </summary>
        public static string TypeConverters_ConvertFrom_CannotConvertFromType1 {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse text &apos;{0}&apos;.
        /// </summary>
        public static string UpDown_ParseException {
            get {
                return ResourceManager.GetString("UpDown_ParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template can only be applied one time..
        /// </summary>
        public static string Viewbox_OnApplyTemplate_OnlyOnce {
            get {
                return ResourceManager.GetString("Viewbox_OnApplyTemplate_OnlyOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid StretchDirection value &apos;{0}&apos;..
        /// </summary>
        public static string Viewbox_OnStretchDirectionPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Viewbox_OnStretchDirectionPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Stretch value &apos;{0}&apos;..
        /// </summary>
        public static string Viewbox_OnStretchPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("Viewbox_OnStretchPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length value &apos;{0}&apos;..
        /// </summary>
        public static string WrapPanel_OnItemHeightOrWidthPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("WrapPanel_OnItemHeightOrWidthPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Orientation value &apos;{0}&apos;..
        /// </summary>
        public static string WrapPanel_OnOrientationPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("WrapPanel_OnOrientationPropertyChanged_InvalidValue", resourceCulture);
            }
        }

        internal static string ImplicitStyleManager_Parse_CanOnlyParseXAMLFilesWithResourceDictionaryAsTheRootElement
        {
            get
            {
                return ResourceManager.GetString("ImplicitStyleManager_Parse_CanOnlyParseXAMLFilesWithResourceDictionaryAsTheRootEl" +
                        "ement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource not found at &apos;{0}&apos;..
        /// </summary>
        internal static string ImplicitStyleManager_ResourceNotFound
        {
            get
            {
                return ResourceManager.GetString("ImplicitStyleManager_ResourceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to load resources..
        /// </summary>
        internal static string InvalidResourceException_UnableToLoadResources
        {
            get
            {
                return ResourceManager.GetString("InvalidResourceException_UnableToLoadResources", resourceCulture);
            }
        }
    }
}
