package Fantasy.Jobs.Properties;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/** 
   A strongly-typed resource class, for looking up localized strings, etc.
 
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources
{

	private static System.Resources.ResourceManager resourceMan;

	private static System.Globalization.CultureInfo resourceCulture;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public Resources()
	{
	}

	/** 
	   Returns the cached ResourceManager instance used by this class.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public static System.Resources.ResourceManager getResourceManager()
	{
		if (Object.ReferenceEquals(resourceMan, null))
		{
			System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Fantasy.Jobs.Properties.Resources", Resources.class.getPackage());
			resourceMan = temp;
		}
		return resourceMan;
	}

	/** 
	   Overrides the current thread's CurrentUICulture property for all
	   resource lookups using this strongly typed resource class.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public static System.Globalization.CultureInfo getCulture()
	{
		return resourceCulture;
	}
	public static void setCulture(System.Globalization.CultureInfo value)
	{
		resourceCulture = value;
	}

	/** 
	   Looks up a localized string similar to Cannot convert parameter {1} of task {0} to TaskItem  .
	 
	*/
	public static String getCannotConverTaskOutputParameterToTaskItemText()
	{
		return getResourceManager().GetString("CannotConverTaskOutputParameterToTaskItemText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Cannot find job template with name &apos;{0}&apos;..
	 
	*/
	public static String getCannotFindTemplateByNameText()
	{
		return getResourceManager().GetString("CannotFindTemplateByNameText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Cannot find job template at {0}..
	 
	*/
	public static String getCannotFindTemplateByPathText()
	{
		return getResourceManager().GetString("CannotFindTemplateByPathText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Cannot set value on MultProgress..
	 
	*/
	public static String getCannotSetValueOnMultProgress()
	{
		return getResourceManager().GetString("CannotSetValueOnMultProgress", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Condition {0} needs at least one required XmlMember..
	 
	*/
	public static String getConditionNeedsOneXmlMemberText()
	{
		return getResourceManager().GetString("ConditionNeedsOneXmlMemberText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Evaluate condition did not return boolean value. Source &quot;{0}&quot;, Parsed &quot;{1}&quot;..
	 
	*/
	public static String getConditionNotBoolText()
	{
		return getResourceManager().GetString("ConditionNotBoolText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Do not support divide exactly operation between {0} and {1}..
	 
	*/
	public static String getDoNotSupportDivideExactlyText()
	{
		return getResourceManager().GetString("DoNotSupportDivideExactlyText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Do not support minus operations on string..
	 
	*/
	public static String getDoNotSupportMinusStringText()
	{
		return getResourceManager().GetString("DoNotSupportMinusStringText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Do not support modulus operation between {0} and {1}..
	 
	*/
	public static String getDoNotSupportModulusText()
	{
		return getResourceManager().GetString("DoNotSupportModulusText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Do not support multiple/divide operations between {0} and {1}..
	 
	*/
	public static String getDoNotSupportMultDivText()
	{
		return getResourceManager().GetString("DoNotSupportMultDivText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Do not support nagetive operation on {0}..
	 
	*/
	public static String getDoNotSupportNagetiveText()
	{
		return getResourceManager().GetString("DoNotSupportNagetiveText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Do not support plus/minus operations between {0} and {1}..
	 
	*/
	public static String getDoNotSupportPlusText()
	{
		return getResourceManager().GetString("DoNotSupportPlusText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to {0} and {1} have same namespace uri &apos;{2}&apos; and name &apos;{3}&apos;..
	 
	*/
	public static String getDulplicateElementText()
	{
		return getResourceManager().GetString("DulplicateElementText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Tasks {0} and {1} have same taks name {2} {3}..
	 
	*/
	public static String getDulplicateTaskText()
	{
		return getResourceManager().GetString("DulplicateTaskText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to File {0} and {1} have same template name {2}..
	 
	*/
	public static String getDulplicateTemplateNamesText()
	{
		return getResourceManager().GetString("DulplicateTemplateNamesText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to {0} and {1} have same xml tag name {2}..
	 
	*/
	public static String getDulplicateXmlTagText()
	{
		return getResourceManager().GetString("DulplicateXmlTagText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Cannot not load template file {0}.
	 
	*/
	public static String getFailToLoadTemplateText()
	{
		return getResourceManager().GetString("FailToLoadTemplateText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to &lt;DSAKeyValue&gt;&lt;P&gt;pNmoVnPhu8rkMqg6uB6WUCm6GqZgzmThr2VC9hk0IBmphxSXZ8hBvjb4L6F44tzWCP5hjh8AuNKvEj/xo0Fxqq1WY7sMeDULf+dpmEK9SF57q4+avzFgo3XD/GBSQmRdbyllJHMw0ByFESAFtth4V3ruProvOyyAuCpyrcm21Ac=&lt;/P&gt;&lt;Q&gt;xGgzJOZHsX7FVrJmF7nD1reKGU0=&lt;/Q&gt;&lt;G&gt;dcAwjh26TA66jjAulcub2HUHGMQgyeIDeTvqPAIrPh08bLO886r8e3hkebnLQY1rDasmgCElbBzCNXZUkyZ2H8EYu8ZYuOSdqn/3r0kL61T6nAdSlac0uYiLL5yLAzzKFhZ9bb+pcvhMG6bOsyokgAp+ATFeR2G6wC4zKuW9ykc=&lt;/G&gt;&lt;Y&gt;ToSNpB4eBi2RW540zqN41+vv7ud/J4KxfQfxmLiF8P7GCV1qaVq8MtM3IPCsmSuN8XfbQhElMWz5x5wqBLBLrnDU0dyg3vhrujLiZLZ [rest of string was truncated]&quot;;.
	 
	*/
	public static String getFantasyPubKey()
	{
		return getResourceManager().GetString("FantasyPubKey", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Task Member with flag Inline must be type of string. Task {0}, Attribute {1}..
	 
	*/
	public static String getInlineTaskMemberMustBeXElementText()
	{
		return getResourceManager().GetString("InlineTaskMemberMustBeXElementText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Input parameter {0} of task {1}  contains {1} TaskItems..
	 
	*/
	public static String getInputParamContainsMultipleItemsText()
	{
		return getResourceManager().GetString("InputParamContainsMultipleItemsText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Input element must set value of  &quot;itemCategory&quot; or &quot;propertyName&quot;.
	 
	*/
	public static String getInvalidCallTemplateInputText()
	{
		return getResourceManager().GetString("InvalidCallTemplateInputText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Invalid expression {0}..
	 
	*/
	public static String getInvalidExpressionText()
	{
		return getResourceManager().GetString("InvalidExpressionText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Invalid filter expression {0}..
	 
	*/
	public static String getInvalidFilterText()
	{
		return getResourceManager().GetString("InvalidFilterText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Job {0} can not transite from {1} to {2}..
	 
	*/
	public static String getInvalidJobTransitionText()
	{
		return getResourceManager().GetString("InvalidJobTransitionText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Step count must be great than 0.
	 
	*/
	public static String getInvalidMultProgressStepCountText()
	{
		return getResourceManager().GetString("InvalidMultProgressStepCountText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Summary of steps must equal 1..
	 
	*/
	public static String getInvalidMultProgressStepsText()
	{
		return getResourceManager().GetString("InvalidMultProgressStepsText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Output element must set value of &quot;itemCategory&quot; or &quot;propertyName&quot;.
	 
	*/
	public static String getInvalidOutputText()
	{
		return getResourceManager().GetString("InvalidOutputText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Progress value must between 0 to 1..
	 
	*/
	public static String getInvalidProgressValueText()
	{
		return getResourceManager().GetString("InvalidProgressValueText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Fantasy.Jobs.Management;
	using Fantasy.Jobs;
	
	namespace Fantasy.Jobs.Temporary
	{
		public class JobMetaDataFilter : IJobMetaDataFilter
		{
	
			#region IJobMetaDataFilter Members
	
			public IEnumerable&lt;JobMetaData&gt; Filter(IQueryable&lt;JobMetaData&gt; source)
			{
				&lt;%=vars%&gt;
	
				var rs = source;
	
				
				&lt;%=enableCondition%&gt;rs = from job in rs wher [rest of string was truncated]&quot;;.
	 
	*/
	public static String getJobMetaDataFilterTemplate()
	{
		return getResourceManager().GetString("JobMetaDataFilterTemplate", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to message.
	 
	*/
	public static String getLogTaskDefaultCategory()
	{
		return getResourceManager().GetString("LogTaskDefaultCategory", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Resource expression {0} missing  name. .
	 
	*/
	public static String getMissingResourceNameText()
	{
		return getResourceManager().GetString("MissingResourceNameText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Must assign target name  because template {0} has not default target..
	 
	*/
	public static String getNoStartupTargetText()
	{
		return getResourceManager().GetString("NoStartupTargetText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to ParseCoditionFailed. Source &quot;{0}&quot;, Parsed &quot;{1}&quot;..
	 
	*/
	public static String getParseConditionFailedText()
	{
		return getResourceManager().GetString("ParseConditionFailedText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Require attribute {0} of task {1}..
	 
	*/
	public static String getRequireAttrubiteOfTaskText()
	{
		return getResourceManager().GetString("RequireAttrubiteOfTaskText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Schedule {0} is already exist..
	 
	*/
	public static String getScheduleExistsText()
	{
		return getResourceManager().GetString("ScheduleExistsText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to A error occurs when set task {0}&apos;s parameter {1}..
	 
	*/
	public static String getSetTaskParamErrorText()
	{
		return getResourceManager().GetString("SetTaskParamErrorText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Undefined tag {0}({1}). Using empty string (&quot;&quot;) as default value..
	 
	*/
	public static String getStringParserUndefinedTagWarningText()
	{
		return getResourceManager().GetString("StringParserUndefinedTagWarningText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Success to load anonymous template file {0}..
	 
	*/
	public static String getSuccessToLoadAnonymousTemplateText()
	{
		return getResourceManager().GetString("SuccessToLoadAnonymousTemplateText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Success to load template file {0}. Template name is {1}..
	 
	*/
	public static String getSuccessToLoadTemplateText()
	{
		return getResourceManager().GetString("SuccessToLoadTemplateText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to An exception occurs while excuting target &apos;{0}&apos; and was ignored..
	 
	*/
	public static String getTargetContinueText()
	{
		return getResourceManager().GetString("TargetContinueText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to An exception occurs while executing target &apos;{0}&apos;, job is terminating..
	 
	*/
	public static String getTargetTermianteText()
	{
		return getResourceManager().GetString("TargetTermianteText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Execute task {0} failed..
	 
	*/
	public static String getTaskFailedText()
	{
		return getResourceManager().GetString("TaskFailedText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Undefined target {0}..
	 
	*/
	public static String getUndefinedTargetText()
	{
		return getResourceManager().GetString("UndefinedTargetText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Task {0} has not output parameter {1}..
	 
	*/
	public static String getUndefinedTaskOutputParameterText()
	{
		return getResourceManager().GetString("UndefinedTaskOutputParameterText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to All try elements are failed, until-success is failed..
	 
	*/
	public static String getUnitlSuccessFailedText()
	{
		return getResourceManager().GetString("UnitlSuccessFailedText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Unkown task or instruction with uri {0} and name {1}..
	 
	*/
	public static String getUnknownTaskText()
	{
		return getResourceManager().GetString("UnknownTaskText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Unresolve function {0}..
	 
	*/
	public static String getUnresolvedFunctionText()
	{
		return getResourceManager().GetString("UnresolvedFunctionText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to All try elements are skipped, until-success is failed..
	 
	*/
	public static String getUntilSuccessAllSkippedText()
	{
		return getResourceManager().GetString("UntilSuccessAllSkippedText", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to &apos;when&apos; instruction requires valid condition..
	 
	*/
	public static String getWhenRequireConditionText()
	{
		return getResourceManager().GetString("WhenRequireConditionText", resourceCulture);
	}
}
