package Fantasy.Jobs.Management;

import Fantasy.XSerialization.*;

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------





//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//[EdmEntityTypeAttribute(NamespaceName="Fantasy.Jobs.Management", Name="JobMetaData"), DataContractAttribute(IsReference=true)]
public class JobMetaData extends EntityObject implements Serializable
{
//C# TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
		///#region Factory Method

	/** 
	 Create a new JobMetaData object.
	 
	 @param id Initial value of the Id property.
	 @param template Initial value of the Template property.
	 @param name Initial value of the Name property.
	 @param state Initial value of the State property.
	 @param creationTime Initial value of the CreationTime property.
	 @param application Initial value of the Application property.
	 @param user Initial value of the User property.
	*/
	public static JobMetaData CreateJobMetaData(System.Guid id, String template, String name, int state, java.util.Date creationTime, String application, String user)
	{
		JobMetaData jobMetaData = new JobMetaData();
		jobMetaData.setId(id);
		jobMetaData.setTemplate(template);
		jobMetaData.setName(name);
		jobMetaData.setState(state);
		jobMetaData.setCreationTime(creationTime);
		jobMetaData.setApplication(application);
		jobMetaData.setUser(user);
		return jobMetaData;
	}

//C# TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
		///#endregion
//C# TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
		///#region Primitive Properties

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false), DataMemberAttribute()]
	public final System.Guid getId()
	{
		return _Id;
	}
	public final void setId(System.Guid value)
	{
		if (!_Id.equals(value))
		{
			OnIdChanging(value);
			ReportPropertyChanging("Id");
			_Id = StructuralObject.SetValidValue(value);
			ReportPropertyChanged("Id");
			OnIdChanged();
		}
	}
	private System.Guid _Id = new System.Guid();
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnIdChanging(System.Guid value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnIdChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true), DataMemberAttribute()]
	public final System.Guid getParentId()
	{
		return _ParentId;
	}
	public final void setParentId(System.Guid value)
	{
		OnParentIdChanging(value);
		ReportPropertyChanging("ParentId");
		_ParentId = StructuralObject.SetValidValue(value);
		ReportPropertyChanged("ParentId");
		OnParentIdChanged();
	}
	private System.Guid _ParentId;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnParentIdChanging(System.Guid value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnParentIdChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false), DataMemberAttribute()]
	public final String getTemplate()
	{
		return _Template;
	}
	public final void setTemplate(String value)
	{
		OnTemplateChanging(value);
		ReportPropertyChanging("Template");
		_Template = StructuralObject.SetValidValue(value, false);
		ReportPropertyChanged("Template");
		OnTemplateChanged();
	}
	private String _Template;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnTemplateChanging(String value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnTemplateChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false), DataMemberAttribute()]
	public final String getName()
	{
		return _Name;
	}
	public final void setName(String value)
	{
		OnNameChanging(value);
		ReportPropertyChanging("Name");
		_Name = StructuralObject.SetValidValue(value, false);
		ReportPropertyChanged("Name");
		OnNameChanged();
	}
	private String _Name;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnNameChanging(String value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnNameChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false), DataMemberAttribute()]
	public final int getState()
	{
		return _State;
	}
	public final void setState(int value)
	{
		OnStateChanging(value);
		ReportPropertyChanging("State");
		_State = StructuralObject.SetValidValue(value);
		ReportPropertyChanged("State");
		OnStateChanged();
	}
	private int _State;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnStateChanging(int value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnStateChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false), DataMemberAttribute()]
	public final int getPriority()
	{
		return _Priority;
	}
	public final void setPriority(int value)
	{
		OnPriorityChanging(value);
		ReportPropertyChanging("Priority");
		_Priority = StructuralObject.SetValidValue(value);
		ReportPropertyChanged("Priority");
		OnPriorityChanged();
	}
	private int _Priority = 0;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnPriorityChanging(int value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnPriorityChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true), DataMemberAttribute()]
	public final java.util.Date getStartTime()
	{
		return _StartTime;
	}
	public final void setStartTime(java.util.Date value)
	{
		OnStartTimeChanging(value);
		ReportPropertyChanging("StartTime");
		_StartTime = StructuralObject.SetValidValue(value);
		ReportPropertyChanged("StartTime");
		OnStartTimeChanged();
	}
	private java.util.Date _StartTime;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnStartTimeChanging(java.util.Date value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnStartTimeChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true), DataMemberAttribute()]
	public final java.util.Date getEndTime()
	{
		return _EndTime;
	}
	public final void setEndTime(java.util.Date value)
	{
		OnEndTimeChanging(value);
		ReportPropertyChanging("EndTime");
		_EndTime = StructuralObject.SetValidValue(value);
		ReportPropertyChanged("EndTime");
		OnEndTimeChanged();
	}
	private java.util.Date _EndTime;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnEndTimeChanging(java.util.Date value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnEndTimeChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false), DataMemberAttribute()]
	public final java.util.Date getCreationTime()
	{
		return _CreationTime;
	}
	public final void setCreationTime(java.util.Date value)
	{
		OnCreationTimeChanging(value);
		ReportPropertyChanging("CreationTime");
		_CreationTime = StructuralObject.SetValidValue(value);
		ReportPropertyChanged("CreationTime");
		OnCreationTimeChanged();
	}
	private java.util.Date _CreationTime = new java.util.Date(0);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnCreationTimeChanging(java.util.Date value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnCreationTimeChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false), DataMemberAttribute()]
	public final String getApplication()
	{
		return _Application;
	}
	public final void setApplication(String value)
	{
		OnApplicationChanging(value);
		ReportPropertyChanging("Application");
		_Application = StructuralObject.SetValidValue(value, false);
		ReportPropertyChanged("Application");
		OnApplicationChanged();
	}
	private String _Application;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnApplicationChanging(String value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnApplicationChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false), DataMemberAttribute()]
	public final String getUser()
	{
		return _User;
	}
	public final void setUser(String value)
	{
		OnUserChanging(value);
		ReportPropertyChanging("User");
		_User = StructuralObject.SetValidValue(value, false);
		ReportPropertyChanged("User");
		OnUserChanged();
	}
	private String _User;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnUserChanging(String value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnUserChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true), DataMemberAttribute()]
	public final String getStartInfo()
	{
		return _StartInfo;
	}
	public final void setStartInfo(String value)
	{
		OnStartInfoChanging(value);
		ReportPropertyChanging("StartInfo");
		_StartInfo = StructuralObject.SetValidValue(value, true);
		ReportPropertyChanged("StartInfo");
		OnStartInfoChanged();
	}
	private String _StartInfo;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnStartInfoChanging(String value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnStartInfoChanged();

	/** 
	 No Metadata Documentation available.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true), DataMemberAttribute()]
	public final String getTag()
	{
		return _Tag;
	}
	public final void setTag(String value)
	{
		OnTagChanging(value);
		ReportPropertyChanging("Tag");
		_Tag = StructuralObject.SetValidValue(value, true);
		ReportPropertyChanged("Tag");
		OnTagChanged();
	}
	private String _Tag;
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnTagChanging(String value);
//C# TO JAVA CONVERTER TODO TASK: Java does not support 'partial' methods.
	partial void OnTagChanged();

//C# TO JAVA CONVERTER TODO TASK: There is no preprocessor in Java:
		///#endregion




	public final boolean getIsTerminated()
	{
		return (this.getState() & JobState.Terminated) == JobState.Terminated;
	}

	private String GetStartInfoProperty(XElement root, String name)
	{
//C# TO JAVA CONVERTER TODO TASK: There is no Java equivalent to LINQ queries:
		XElement element = (from props in root.Elements() where props.getName().LocalName.equals("properties") from prop in props.Elements() where StringComparer.OrdinalIgnoreCase.Compare(prop.getName().LocalName, name) == 0 select prop).SingleOrDefault();

		return element != null ? (String)element : null;
	}


	public final void LoadXml(String xml)
	{
		XElement root = XElement.Parse(xml);


		Guid id = (root.Attribute("id") != null && ! (String)root.Attribute("id").equals("")) ? (Guid)root.Attribute("id") : Guid.Empty;
		if (id.equals(Guid.Empty))
		{
			id = Guid.NewGuid();
		}
		this.setId(id);
		this.setTemplate((String)root.Attribute("template"));

		if (String.IsNullOrWhiteSpace(this.getTemplate()))
		{
			throw new JobException("Missing job template");
		}

		String name = this.GetStartInfoProperty(root, "name");

		this.setName((name != null) ? name : this.getTemplate());

		try
		{

			this.setApplication(this.GetStartInfoProperty(root, "application"));
		}
		catch (java.lang.Exception e)
		{
			throw new JobException("Missing job application");
		}


		this.setCreationTime(new java.util.Date());
		this.setState(JobState.Unstarted);


		try
		{
			this.setUser(this.GetStartInfoProperty(root, "user"));
		}
		catch (java.lang.Exception e2)
		{
			throw new JobException("Missing job user");
		}

		String sp = this.GetStartInfoProperty(root, "priority");
		int priority = 0;
		RefObject<Integer> tempRef_priority = new RefObject<Integer>(priority);
		boolean tempVar = sp != null && Integer.TryParse(sp, tempRef_priority);
			priority = tempRef_priority.argvalue;
		if (tempVar)
		{
			this.setPriority(priority);
		}

		this.setStartInfo(xml);

		this.setTag(this.GetStartInfoProperty(root, "tag"));
	}

}