//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.Jobs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantasy.Jobs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert parameter {1} of task {0} to TaskItem  .
        /// </summary>
        internal static string CannotConverTaskOutputParameterToTaskItemText {
            get {
                return ResourceManager.GetString("CannotConverTaskOutputParameterToTaskItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find job template with name &apos;{0}&apos;..
        /// </summary>
        internal static string CannotFindTemplateByNameText {
            get {
                return ResourceManager.GetString("CannotFindTemplateByNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find job template at {0}..
        /// </summary>
        internal static string CannotFindTemplateByPathText {
            get {
                return ResourceManager.GetString("CannotFindTemplateByPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set value on MultProgress..
        /// </summary>
        internal static string CannotSetValueOnMultProgress {
            get {
                return ResourceManager.GetString("CannotSetValueOnMultProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition {0} needs at least one required XmlMember..
        /// </summary>
        internal static string ConditionNeedsOneXmlMemberText {
            get {
                return ResourceManager.GetString("ConditionNeedsOneXmlMemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate condition did not return boolean value. Source &quot;{0}&quot;, Parsed &quot;{1}&quot;..
        /// </summary>
        internal static string ConditionNotBoolText {
            get {
                return ResourceManager.GetString("ConditionNotBoolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support divide exactly operation between {0} and {1}..
        /// </summary>
        internal static string DoNotSupportDivideExactlyText {
            get {
                return ResourceManager.GetString("DoNotSupportDivideExactlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support minus operations on string..
        /// </summary>
        internal static string DoNotSupportMinusStringText {
            get {
                return ResourceManager.GetString("DoNotSupportMinusStringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support modulus operation between {0} and {1}..
        /// </summary>
        internal static string DoNotSupportModulusText {
            get {
                return ResourceManager.GetString("DoNotSupportModulusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support multiple/divide operations between {0} and {1}..
        /// </summary>
        internal static string DoNotSupportMultDivText {
            get {
                return ResourceManager.GetString("DoNotSupportMultDivText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support nagetive operation on {0}..
        /// </summary>
        internal static string DoNotSupportNagetiveText {
            get {
                return ResourceManager.GetString("DoNotSupportNagetiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not support plus/minus operations between {0} and {1}..
        /// </summary>
        internal static string DoNotSupportPlusText {
            get {
                return ResourceManager.GetString("DoNotSupportPlusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} have same namespace uri &apos;{2}&apos; and name &apos;{3}&apos;..
        /// </summary>
        internal static string DulplicateElementText {
            get {
                return ResourceManager.GetString("DulplicateElementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks {0} and {1} have same taks name {2} {3}..
        /// </summary>
        internal static string DulplicateTaskText {
            get {
                return ResourceManager.GetString("DulplicateTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} and {1} have same template name {2}..
        /// </summary>
        internal static string DulplicateTemplateNamesText {
            get {
                return ResourceManager.GetString("DulplicateTemplateNamesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} have same xml tag name {2}..
        /// </summary>
        internal static string DulplicateXmlTagText {
            get {
                return ResourceManager.GetString("DulplicateXmlTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot not load template file {0}.
        /// </summary>
        internal static string FailToLoadTemplateText {
            get {
                return ResourceManager.GetString("FailToLoadTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Member with flag Inline must be type of string. Task {0}, Attribute {1}..
        /// </summary>
        internal static string InlineTaskMemberMustBeXElementText {
            get {
                return ResourceManager.GetString("InlineTaskMemberMustBeXElementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameter {0} of task {1}  contains {1} TaskItems..
        /// </summary>
        internal static string InputParamContainsMultipleItemsText {
            get {
                return ResourceManager.GetString("InputParamContainsMultipleItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input element must set value of  &quot;itemCategory&quot; or &quot;propertyName&quot;.
        /// </summary>
        internal static string InvalidCallTemplateInputText {
            get {
                return ResourceManager.GetString("InvalidCallTemplateInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression {0}..
        /// </summary>
        internal static string InvalidExpressionText {
            get {
                return ResourceManager.GetString("InvalidExpressionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filter expression {0}..
        /// </summary>
        internal static string InvalidFilterText {
            get {
                return ResourceManager.GetString("InvalidFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job {0} can not transite from {1} to {2}..
        /// </summary>
        internal static string InvalidJobTransitionText {
            get {
                return ResourceManager.GetString("InvalidJobTransitionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step count must be great than 0.
        /// </summary>
        internal static string InvalidMultProgressStepCountText {
            get {
                return ResourceManager.GetString("InvalidMultProgressStepCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of steps must equal 1..
        /// </summary>
        internal static string InvalidMultProgressStepsText {
            get {
                return ResourceManager.GetString("InvalidMultProgressStepsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output element must set value of &quot;itemCategory&quot; or &quot;propertyName&quot;.
        /// </summary>
        internal static string InvalidOutputText {
            get {
                return ResourceManager.GetString("InvalidOutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress value must between 0 to 1..
        /// </summary>
        internal static string InvalidProgressValueText {
            get {
                return ResourceManager.GetString("InvalidProgressValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using Fantasy.Jobs.Management;
        ///using Fantasy.Jobs;
        ///
        ///namespace Fantasy.Jobs.Temporary
        ///{
        ///    public class JobMetaDataFilter : IJobMetaDataFilter
        ///    {
        ///
        ///        #region IJobMetaDataFilter Members
        ///
        ///        public IEnumerable&lt;JobMetaData&gt; Filter(IQueryable&lt;JobMetaData&gt; source)
        ///        {
        ///            &lt;%=vars%&gt;
        ///
        ///            var rs = source;
        ///
        ///            
        ///            &lt;%=enableCondition%&gt;rs = from job in r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobMetaDataFilterTemplate {
            get {
                return ResourceManager.GetString("JobMetaDataFilterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string LogTaskDefaultCategory {
            get {
                return ResourceManager.GetString("LogTaskDefaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource expression {0} missing  name. .
        /// </summary>
        internal static string MissingResourceNameText {
            get {
                return ResourceManager.GetString("MissingResourceNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must assign target name  because template {0} has not default target..
        /// </summary>
        internal static string NoStartupTargetText {
            get {
                return ResourceManager.GetString("NoStartupTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParseCoditionFailed. Source &quot;{0}&quot;, Parsed &quot;{1}&quot;..
        /// </summary>
        internal static string ParseConditionFailedText {
            get {
                return ResourceManager.GetString("ParseConditionFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require attribute {0} of task {1}..
        /// </summary>
        internal static string RequireAttrubiteOfTaskText {
            get {
                return ResourceManager.GetString("RequireAttrubiteOfTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule {0} is already exist..
        /// </summary>
        internal static string ScheduleExistsText {
            get {
                return ResourceManager.GetString("ScheduleExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A error occurs when set task {0}&apos;s parameter {1}..
        /// </summary>
        internal static string SetTaskParamErrorText {
            get {
                return ResourceManager.GetString("SetTaskParamErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined tag {0}({1}). Using empty string (&quot;&quot;) as default value..
        /// </summary>
        internal static string StringParserUndefinedTagWarningText {
            get {
                return ResourceManager.GetString("StringParserUndefinedTagWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success to load anonymous template file {0}..
        /// </summary>
        internal static string SuccessToLoadAnonymousTemplateText {
            get {
                return ResourceManager.GetString("SuccessToLoadAnonymousTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success to load template file {0}. Template name is {1}..
        /// </summary>
        internal static string SuccessToLoadTemplateText {
            get {
                return ResourceManager.GetString("SuccessToLoadTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurs while excuting target &apos;{0}&apos; and was ignored..
        /// </summary>
        internal static string TargetContinueText {
            get {
                return ResourceManager.GetString("TargetContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurs while executing target &apos;{0}&apos;, job is terminating..
        /// </summary>
        internal static string TargetTermianteText {
            get {
                return ResourceManager.GetString("TargetTermianteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute task {0} failed..
        /// </summary>
        internal static string TaskFailedText {
            get {
                return ResourceManager.GetString("TaskFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined target {0}..
        /// </summary>
        internal static string UndefinedTargetText {
            get {
                return ResourceManager.GetString("UndefinedTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} has not output parameter {1}..
        /// </summary>
        internal static string UndefinedTaskOutputParameterText {
            get {
                return ResourceManager.GetString("UndefinedTaskOutputParameterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All try elements are failed, until-success is failed..
        /// </summary>
        internal static string UnitlSuccessFailedText {
            get {
                return ResourceManager.GetString("UnitlSuccessFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown task or instruction with uri {0} and name {1}..
        /// </summary>
        internal static string UnknownTaskText {
            get {
                return ResourceManager.GetString("UnknownTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolve function {0}..
        /// </summary>
        internal static string UnresolvedFunctionText {
            get {
                return ResourceManager.GetString("UnresolvedFunctionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All try elements are skipped, until-success is failed..
        /// </summary>
        internal static string UntilSuccessAllSkippedText {
            get {
                return ResourceManager.GetString("UntilSuccessAllSkippedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;when&apos; instruction requires valid condition..
        /// </summary>
        internal static string WhenRequireConditionText {
            get {
                return ResourceManager.GetString("WhenRequireConditionText", resourceCulture);
            }
        }
    }
}
