//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.Studio.BusinessEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantasy.Studio.BusinessEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly File |*.dll.
        /// </summary>
        public static string AddReferenceDialogFilter {
            get {
                return ResourceManager.GetString("AddReferenceDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Reference.
        /// </summary>
        public static string AddReferenceDialogTitle {
            get {
                return ResourceManager.GetString("AddReferenceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string ApplicationFolderName {
            get {
                return ResourceManager.GetString("ApplicationFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associations.
        /// </summary>
        public static string AssociationFolderName {
            get {
                return ResourceManager.GetString("AssociationFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string BusinessPropertyEditorTitle {
            get {
                return ResourceManager.GetString("BusinessPropertyEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string BusinessRolePanelTitle {
            get {
                return ResourceManager.GetString("BusinessRolePanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string BusinessUserPanelTitle {
            get {
                return ResourceManager.GetString("BusinessUserPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string ClassDiagramPanelTitle {
            get {
                return ResourceManager.GetString("ClassDiagramPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class View.
        /// </summary>
        public static string ClassViewPadTitle {
            get {
                return ResourceManager.GetString("ClassViewPadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should save following changes before import Visual Studio project:.
        /// </summary>
        public static string ConfirmImportProjectMessage {
            get {
                return ResourceManager.GetString("ConfirmImportProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string DefaultCodePanelTitle {
            get {
                return ResourceManager.GetString("DefaultCodePanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Application.
        /// </summary>
        public static string DefaultNewBusinessApplicationName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Association.
        /// </summary>
        public static string DefaultNewBusinessAssociationName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessAssociationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Class Diagram.
        /// </summary>
        public static string DefaultNewBusinessClassDiagramName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessClassDiagramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Class.
        /// </summary>
        public static string DefaultNewBusinessClassName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Enum.
        /// </summary>
        public static string DefaultNewBusinessEnumName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Value.
        /// </summary>
        public static string DefaultNewBusinessEnumValueName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessEnumValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Package.
        /// </summary>
        public static string DefaultNewBusinessPackageName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Property.
        /// </summary>
        public static string DefaultNewBusinessPropertyName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewRole.
        /// </summary>
        public static string DefaultNewBusinessRoleName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewUser.
        /// </summary>
        public static string DefaultNewBusinessUserName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewController.
        /// </summary>
        public static string DefaultNewBusinessWebControllerName {
            get {
                return ResourceManager.GetString("DefaultNewBusinessWebControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultParticipantACLPanelTitle {
            get {
                return ResourceManager.GetString("DefaultParticipantACLPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string DefaultStandardWebFolderName {
            get {
                return ResourceManager.GetString("DefaultStandardWebFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Model.
        /// </summary>
        public static string DocumentPadTitle {
            get {
                return ResourceManager.GetString("DocumentPadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string EnumValuesPanelTitle {
            get {
                return ResourceManager.GetString("EnumValuesPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Model.
        /// </summary>
        public static string ObjectModelFolderName {
            get {
                return ResourceManager.GetString("ObjectModelFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string ParticipantPanelTitle {
            get {
                return ResourceManager.GetString("ParticipantPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string PropertyGridEditorDefaultTitle {
            get {
                return ResourceManager.GetString("PropertyGridEditorDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleFolderName {
            get {
                return ResourceManager.GetString("RoleFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        public static string ScriptFolderName {
            get {
                return ResourceManager.GetString("ScriptFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution File | *.sln.
        /// </summary>
        public static string SolutionFileDialogFilter {
            get {
                return ResourceManager.GetString("SolutionFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select solution file path.
        /// </summary>
        public static string SolutionFileDialogTitle {
            get {
                return ResourceManager.GetString("SolutionFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserFolderName {
            get {
                return ResourceManager.GetString("UserFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and Roles.
        /// </summary>
        public static string UserRoleFolderName {
            get {
                return ResourceManager.GetString("UserRoleFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string WebFolderName {
            get {
                return ResourceManager.GetString("WebFolderName", resourceCulture);
            }
        }
    }
}
