//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.Web.Testing.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/About.cshtml")]
    public class _Page_Views_Home_About_cshtml : System.Web.Mvc.WebViewPage
    {
#line hidden
        public _Page_Views_Home_About_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {

            
            #line 1 "D:\Fantasy\Andean\Fantasy.Web.Testing\Views\Home\About.cshtml"
  
    ViewBag.Title = "About Us";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/About.cshtml", 38, 36, true);

WriteLiteral("\r\n\r\n<hgroup class=\"title\">\r\n    <h1>");

EndContext("~/Views/Home/About.cshtml", 38, 36, true);

BeginContext("~/Views/Home/About.cshtml", 75, 13, false);

            
            #line 6 "D:\Fantasy\Andean\Fantasy.Web.Testing\Views\Home\About.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 75, 13, false);

BeginContext("~/Views/Home/About.cshtml", 88, 16, true);

WriteLiteral(".</h1>\r\n    <h2>");

EndContext("~/Views/Home/About.cshtml", 88, 16, true);

BeginContext("~/Views/Home/About.cshtml", 105, 15, false);

            
            #line 7 "D:\Fantasy\Andean\Fantasy.Web.Testing\Views\Home\About.cshtml"
   Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 105, 15, false);

BeginContext("~/Views/Home/About.cshtml", 120, 3093, true);

WriteLiteral("</h2>\r\n</hgroup>\r\n\r\n<article>\r\n    <p>\r\n        Lorem ipsum dolor sit amet, conse" +
"ctetur adipiscing elit. Proin luctus tincidunt justo nec tempor. \r\n        Aliqu" +
"am erat volutpat. Fusce facilisis ullamcorper consequat. Vestibulum non sapien l" +
"ectus. Nam \r\n        mi augue, posuere at tempus vel, dignissim vitae nulla. Nul" +
"lam at quam eu sapien mattis ultrices. \r\n        Quisque quis leo mi, at loborti" +
"s dolor. Nullam scelerisque facilisis placerat. Fusce a augue \r\n        erat, ma" +
"lesuada euismod dui. Duis iaculis risus id felis volutpat elementum. Fusce bland" +
"it iaculis \r\n        quam a cursus. Cras varius tincidunt cursus. Morbi justo er" +
"os, adipiscing ac placerat sed, posuere \r\n        et mi. Suspendisse vulputate v" +
"iverra aliquet. Duis non enim a nibh consequat mollis ac tempor \r\n        lorem." +
" Phasellus elit leo, semper eu luctus et, suscipit at lacus. In hac habitasse pl" +
"atea \r\n        dictumst. Duis dignissim justo sit amet nulla pulvinar sodales.\r\n" +
"    </p>\r\n\r\n    <p>\r\n        Lorem ipsum dolor sit amet, consectetur adipiscing " +
"elit. Proin luctus tincidunt justo nec tempor. \r\n        Aliquam erat volutpat. " +
"Fusce facilisis ullamcorper consequat. Vestibulum non sapien lectus. Nam \r\n     " +
"   mi augue, posuere at tempus vel, dignissim vitae nulla. Nullam at quam eu sap" +
"ien mattis ultrices. \r\n        Quisque quis leo mi, at lobortis dolor. Nullam sc" +
"elerisque facilisis placerat. Fusce a augue \r\n        erat, malesuada euismod du" +
"i. Duis iaculis risus id felis volutpat elementum. Fusce blandit iaculis \r\n     " +
"   quam a cursus. Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac " +
"placerat sed, posuere \r\n        et mi. Suspendisse vulputate viverra aliquet. Du" +
"is non enim a nibh consequat mollis ac tempor \r\n        lorem. Phasellus elit le" +
"o, semper eu luctus et, suscipit at lacus. In hac habitasse platea \r\n        dic" +
"tumst. Duis dignissim justo sit amet nulla pulvinar sodales.\r\n    </p>\r\n\r\n    <p" +
">\r\n        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus" +
" tincidunt justo nec tempor. \r\n        Aliquam erat volutpat. Fusce facilisis ul" +
"lamcorper consequat. Vestibulum non sapien lectus. Nam \r\n        mi augue, posue" +
"re at tempus vel, dignissim vitae nulla. Nullam at quam eu sapien mattis ultrice" +
"s. \r\n        Quisque quis leo mi, at lobortis dolor. Nullam scelerisque facilisi" +
"s placerat. Fusce a augue \r\n        erat, malesuada euismod dui. Duis iaculis ri" +
"sus id felis volutpat elementum. Fusce blandit iaculis \r\n        quam a cursus. " +
"Cras varius tincidunt cursus. Morbi justo eros, adipiscing ac placerat sed, posu" +
"ere \r\n        et mi. Suspendisse vulputate viverra aliquet. Duis non enim a nibh" +
" consequat mollis ac tempor \r\n        lorem. Phasellus elit leo, semper eu luctu" +
"s et, suscipit at lacus. In hac habitasse platea \r\n        dictumst. Duis dignis" +
"sim justo sit amet nulla pulvinar sodales.\r\n    </p>\r\n</article>\r\n\r\n<aside>\r\n   " +
" <h3>Aside Title</h3>\r\n    <p>\r\n        Fusce facilisis ullamcorper consequat. V" +
"estibulum non sapien lectus. Nam \r\n        mi augue, posuere at tempus vel, dign" +
"issim vitae nulla.\r\n    </p>\r\n    <ul>\r\n        <li>");

EndContext("~/Views/Home/About.cshtml", 120, 3093, true);

BeginContext("~/Views/Home/About.cshtml", 3214, 40, false);

            
            #line 55 "D:\Fantasy\Andean\Fantasy.Web.Testing\Views\Home\About.cshtml"
       Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 3214, 40, false);

BeginContext("~/Views/Home/About.cshtml", 3254, 19, true);

WriteLiteral("</li>\r\n        <li>");

EndContext("~/Views/Home/About.cshtml", 3254, 19, true);

BeginContext("~/Views/Home/About.cshtml", 3274, 41, false);

            
            #line 56 "D:\Fantasy\Andean\Fantasy.Web.Testing\Views\Home\About.cshtml"
       Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 3274, 41, false);

BeginContext("~/Views/Home/About.cshtml", 3315, 19, true);

WriteLiteral("</li>\r\n        <li>");

EndContext("~/Views/Home/About.cshtml", 3315, 19, true);

BeginContext("~/Views/Home/About.cshtml", 3335, 45, false);

            
            #line 57 "D:\Fantasy\Andean\Fantasy.Web.Testing\Views\Home\About.cshtml"
       Write(Html.ActionLink("Contact", "Contact", "Home"));

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 3335, 45, false);

BeginContext("~/Views/Home/About.cshtml", 3380, 26, true);

WriteLiteral("</li>\r\n    </ul>\r\n</aside>");

EndContext("~/Views/Home/About.cshtml", 3380, 26, true);

        }
    }
}
