#region Copyright Syncfusion Inc. 2001 - 2011
// Copyright Syncfusion Inc. 2001 - 2011. All rights reserved.
// Use of this code is subject to the terms of our license.
// A copy of the current license can be obtained at any time by e-mailing
// licensing@syncfusion.com. Any infringement will be prosecuted under
// applicable laws. 
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncfusion.Windows.Diagram.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syncfusion_Diagram_Wpf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syncfusion_Diagram_Wpf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syncfusion.Windows.Diagram.Resources.Syncfusion.Diagram.Wpf", typeof(Syncfusion_Diagram_Wpf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string ContextMenu_Grouping {
            get {
                return ResourceManager.GetString("ContextMenu_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string ContextMenu_Grouping_Group {
            get {
                return ResourceManager.GetString("ContextMenu_Grouping_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        internal static string ContextMenu_Grouping_Ungroup {
            get {
                return ResourceManager.GetString("ContextMenu_Grouping_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string ContextMenu_Order {
            get {
                return ResourceManager.GetString("ContextMenu_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Forward.
        /// </summary>
        internal static string ContextMenu_Order_BringForward {
            get {
                return ResourceManager.GetString("ContextMenu_Order_BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring To Front.
        /// </summary>
        internal static string ContextMenu_Order_BringToFront {
            get {
                return ResourceManager.GetString("ContextMenu_Order_BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Backward.
        /// </summary>
        internal static string ContextMenu_Order_SendBackward {
            get {
                return ResourceManager.GetString("ContextMenu_Order_SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Back.
        /// </summary>
        internal static string ContextMenu_Order_SendToBack {
            get {
                return ResourceManager.GetString("ContextMenu_Order_SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SymbolPaletteFilter_All {
            get {
                return ResourceManager.GetString("SymbolPaletteFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectors.
        /// </summary>
        internal static string SymbolPaletteFilter_Connectors {
            get {
                return ResourceManager.GetString("SymbolPaletteFilter_Connectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Shapes.
        /// </summary>
        internal static string SymbolPaletteFilter_CustomShapes {
            get {
                return ResourceManager.GetString("SymbolPaletteFilter_CustomShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Shapes.
        /// </summary>
        internal static string SymbolPaletteFilter_ElectricalShapes {
            get {
                return ResourceManager.GetString("SymbolPaletteFilter_ElectricalShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart.
        /// </summary>
        internal static string SymbolPaletteFilter_Flowchart {
            get {
                return ResourceManager.GetString("SymbolPaletteFilter_Flowchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        internal static string SymbolPaletteFilter_Shapes {
            get {
                return ResourceManager.GetString("SymbolPaletteFilter_Shapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectors.
        /// </summary>
        internal static string SymbolPaletteGroup_Connectors {
            get {
                return ResourceManager.GetString("SymbolPaletteGroup_Connectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Shapes.
        /// </summary>
        internal static string SymbolPaletteGroup_CustomShapes {
            get {
                return ResourceManager.GetString("SymbolPaletteGroup_CustomShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Shapes.
        /// </summary>
        internal static string SymbolPaletteGroup_ElectricalShapes {
            get {
                return ResourceManager.GetString("SymbolPaletteGroup_ElectricalShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart.
        /// </summary>
        internal static string SymbolPaletteGroup_Flowchart {
            get {
                return ResourceManager.GetString("SymbolPaletteGroup_Flowchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        internal static string SymbolPaletteGroup_Shapes {
            get {
                return ResourceManager.GetString("SymbolPaletteGroup_Shapes", resourceCulture);
            }
        }
    }
}
