//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.Web.Mvc {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class DependencyPathSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DependencyPathSettings defaultInstance = ((DependencyPathSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DependencyPathSettings())));
        
        public static DependencyPathSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.addin.xaml")]
        public string Path {
            get {
                return ((string)(this["Path"]));
            }
        }
    }
}
