package Fantasy.Configuration;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



//     Runtime Version:4.0.30319.1
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//[System.Runtime.CompilerServices.CompilerGeneratedAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
public final class sample extends System.Configuration.ApplicationSettingsBase implements Fantasy.Configuration.SettingsBase
{

	private static sample defaultInstance = ((sample)(System.Configuration.ApplicationSettingsBase.Synchronized(new sample())));

	public static sample getDefault()
	{
		return defaultInstance;
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Fantasy\\JobService\\Template")]
	public String getJobTemplateDirectory()
	{
		return ((String)(this["JobTemplateDirectory"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Fantasy\\JobService\\Job")]
	public String getJobDirectory()
	{
		return ((String)(this["JobDirectory"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Fantasy\\JobService\\Log")]
	public String getLogDirectory()
	{
		return ((String)(this["LogDirectory"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("6")]
	public int getJobProcessCount()
	{
		return ((int)(this["JobProcessCount"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute(".\\Fantasy.Jobs.JobHost.exe")]
	public String getJobHostPath()
	{
		return ((String)(this["JobHostPath"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("")]
	public String getStartupFolders()
	{
		return ((String)(this["StartupFolders"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Schedule")]
	public String getScheduleDirectory()
	{
		return ((String)(this["ScheduleDirectory"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\ScheduleTemplate")]
	public String getScheduleTemplateDirectory()
	{
		return ((String)(this["ScheduleTemplateDirectory"]));
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.ApplicationScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>" + "\r\n" + "<ArrayOfString xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "</ArrayOfString>")]
	public System.Collections.Specialized.StringCollection getstrings()
	{
		return ((System.Collections.Specialized.StringCollection)(this["strings"]));
	}


	private static sample _default = (sample)Fantasy.Configuration.SettingStorage.Load(new sample());

	public static sample getDefault()
	{
		return _default;
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Fantasy\\JobService\\Template")]
	public String getJobTemplateDirectory()
	{
		return (String)this.GetValue("JobTemplateDirectory");
	}
	public void setJobTemplateDirectory(String value)
	{
		this.SetValue("JobTemplateDirectory", value);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Fantasy\\JobService\\Job")]
	public String getJobDirectory()
	{
		return (String)this.GetValue("JobDirectory");
	}
	public void setJobDirectory(String value)
	{
		this.SetValue("JobDirectory", value);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Fantasy\\JobService\\Log")]
	public String getLogDirectory()
	{
		return (String)this.GetValue("LogDirectory");
	}
	public void setLogDirectory(String value)
	{
		this.SetValue("LogDirectory", value);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute("6")]
	public int getJobProcessCount()
	{
		return (int)this.GetValue("JobProcessCount");
	}
	public void setJobProcessCount(int value)
	{
		this.SetValue("JobProcessCount", value);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute(".\\Fantasy.Jobs.JobHost.exe")]
	public String getJobHostPath()
	{
		return (String)this.GetValue("JobHostPath");
	}
	public void setJobHostPath(String value)
	{
		this.SetValue("JobHostPath", value);
	}

	public String getStartupFolders()
	{
		return (String)this.GetValue("StartupFolders");
	}
	public void setStartupFolders(String value)
	{
		this.SetValue("StartupFolders", value);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\Schedule")]
	public String getScheduleDirectory()
	{
		return (String)this.GetValue("ScheduleDirectory");
	}
	public void setScheduleDirectory(String value)
	{
		this.SetValue("ScheduleDirectory", value);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute("%ALLUSERSPROFILE%\\Application Data\\ScheduleTemplate")]
	public String getScheduleTemplateDirectory()
	{
		return (String)this.GetValue("ScheduleTemplateDirectory");
	}
	public void setScheduleTemplateDirectory(String value)
	{
		this.SetValue("ScheduleTemplateDirectory", value);
	}

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>" + "\r\n" + "<ArrayOfString xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "  <string>asdf</string>" + "\r\n" + "</ArrayOfString>")]
	public System.Collections.Specialized.StringCollection getstrings()
	{
		return (System.Collections.Specialized.StringCollection)this.GetValue("strings");
	}

}