//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fantasy.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; cannot be null or empty string (&quot;&quot;)..
        /// </summary>
        public static string ArgumentNullOrEmptyStringText {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmptyStringText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string AuthenticationFailedMessage {
            get {
                return ResourceManager.GetString("AuthenticationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string BooleanEditorDefaultFalseText {
            get {
                return ResourceManager.GetString("BooleanEditorDefaultFalseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        public static string BooleanEditorDefaultNullText {
            get {
                return ResourceManager.GetString("BooleanEditorDefaultNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string BooleanEditorDefaultTrueText {
            get {
                return ResourceManager.GetString("BooleanEditorDefaultTrueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox for editing boolean value..
        /// </summary>
        public static string BooleanEditorDescription {
            get {
                return ResourceManager.GetString("BooleanEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string BooleanEditorName {
            get {
                return ResourceManager.GetString("BooleanEditorName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap BusinessObjectEditorIcon {
            get {
                object obj = ResourceManager.GetObject("BusinessObjectEditorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show user name.
        /// </summary>
        public static string BusinessUserEditorDescription {
            get {
                return ResourceManager.GetString("BusinessUserEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string BusinessUserEditorName {
            get {
                return ResourceManager.GetString("BusinessUserEditorName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap CheckBox {
            get {
                object obj = ResourceManager.GetObject("CheckBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ClassIdEditor {
            get {
                object obj = ResourceManager.GetObject("ClassIdEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show object class name..
        /// </summary>
        public static string ClassIdEditorDescription {
            get {
                return ResourceManager.GetString("ClassIdEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassIdEditorName {
            get {
                return ResourceManager.GetString("ClassIdEditorName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap DateTimePicker {
            get {
                object obj = ResourceManager.GetObject("DateTimePicker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap EditorIcon {
            get {
                object obj = ResourceManager.GetObject("EditorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogInModel_Password {
            get {
                return ResourceManager.GetString("LogInModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remeber me?.
        /// </summary>
        public static string LogInModel_RememberMe {
            get {
                return ResourceManager.GetString("LogInModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string LogInModel_UserName {
            get {
                return ResourceManager.GetString("LogInModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string NewBusinessObjectName {
            get {
                return ResourceManager.GetString("NewBusinessObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object Selector. Application : {0}({1}), Entry Object : {0} ({1}).
        /// </summary>
        public static string ObjectEditorDescriptor {
            get {
                return ResourceManager.GetString("ObjectEditorDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Object Selector.
        /// </summary>
        public static string ObjectEditorName {
            get {
                return ResourceManager.GetString("ObjectEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no property/association named {0} in business class {1}..
        /// </summary>
        public static string PropertyNotFoundMessage {
            get {
                return ResourceManager.GetString("PropertyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; does not exist.
        /// </summary>
        public static string RoleDoesNotExistMessage {
            get {
                return ResourceManager.GetString("RoleDoesNotExistMessage", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Selector {
            get {
                object obj = ResourceManager.GetObject("Selector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        public static string StandardNavigationAddChildText {
            get {
                return ResourceManager.GetString("StandardNavigationAddChildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard View.
        /// </summary>
        public static string StandardNavigationName {
            get {
                return ResourceManager.GetString("StandardNavigationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Selection View.
        /// </summary>
        public static string StandardSelectionName {
            get {
                return ResourceManager.GetString("StandardSelectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1} is not type of BusinessObject..
        /// </summary>
        public static string StdSelInvalidPropertyText {
            get {
                return ResourceManager.GetString("StdSelInvalidPropertyText", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap TextArea {
            get {
                object obj = ResourceManager.GetObject("TextArea", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic single line text editor..
        /// </summary>
        public static string TextEditorDescription {
            get {
                return ResourceManager.GetString("TextEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        public static string TextEditorName {
            get {
                return ResourceManager.GetString("TextEditorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not exist..
        /// </summary>
        public static string UserDoesNotExistMessage {
            get {
                return ResourceManager.GetString("UserDoesNotExistMessage", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap UserEditor {
            get {
                object obj = ResourceManager.GetObject("UserEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ValidationIcon {
            get {
                object obj = ResourceManager.GetObject("ValidationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution of the child request failed. Please examine the InnerException for more information..
        /// </summary>
        public static string ViewPageHttpHandlerWrapper_ExceptionOccurred {
            get {
                return ResourceManager.GetString("ViewPageHttpHandlerWrapper_ExceptionOccurred", resourceCulture);
            }
        }
    }
}
