using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyInformationalVersionAttribute("1.0.0.32")]
[assembly: AssemblyCompanyAttribute("ClickView Pty Limited")]
[assembly: AssemblyProductAttribute("ClickView Synchroniser (Job Service)")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2003-2012 ClickView Pty Limited. All rights reserved.")]
[assembly: AssemblyTrademarkAttribute("ClickView Synchroniser (Job Service) is a registered trademark of ClickView Pty L" +
    "imited")]

