package fantasy.jobs;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/** 
   A strongly-typed resource class, for looking up localized strings, etc.
 
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class LogCategories
{

	private static System.Resources.ResourceManager resourceMan;

	private static System.Globalization.CultureInfo resourceCulture;

//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
	public LogCategories()
	{
	}

	/** 
	   Returns the cached ResourceManager instance used by this class.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public static System.Resources.ResourceManager getResourceManager()
	{
		if (Object.ReferenceEquals(resourceMan, null))
		{
			System.Resources.ResourceManager temp = new System.Resources.ResourceManager("fantasy.jobs.LogCategories", LogCategories.class.getPackage());
			resourceMan = temp;
		}
		return resourceMan;
	}

	/** 
	   Overrides the current thread's CurrentUICulture property for all
	   resource lookups using this strongly typed resource class.
	 
	*/
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
	//[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
	public static System.Globalization.CultureInfo getCulture()
	{
		return resourceCulture;
	}
	public static void setCulture(System.Globalization.CultureInfo value)
	{
		resourceCulture = value;
	}

	/** 
	   Looks up a localized string similar to CustomError.
	 
	*/
	public static String getCustomError()
	{
		return getResourceManager().GetString("CustomError", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Engine.
	 
	*/
	public static String getEngine()
	{
		return getResourceManager().GetString("Engine", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Instruction.
	 
	*/
	public static String getInstruction()
	{
		return getResourceManager().GetString("Instruction", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to LogTask.
	 
	*/
	public static String getLogTask()
	{
		return getResourceManager().GetString("LogTask", resourceCulture);
	}

	/** 
	   Looks up a localized string similar to Manager.
	 
	*/
	public static String getManager()
	{
		return getResourceManager().GetString("Manager", resourceCulture);
	}
}